### ISSUE TITLE
Can the setup routine please fail silently?

### ISSUE THREAD

**Issue by ri0t** [google/python-subprocess32#11]
Otherwise continuous integration with this thing included needs an unnecessary complex way of discerning 2.7 & 3.x dependencies - i.e. I don't want to have a seperate requirements.txt for 2.x.. Or is there something i missed?

**Comment by gpshead** [comment]
I assume you're talking about this setup.py code?

```python
    if sys.version_info[0] != 2:
        sys.stderr.write('This backport is for Python 2.x only.\n')
        sys.exit(1)
```

Desiring not to add conditional requirements (excluding subprocess32) to your own project that works on Python 3?

How are you specifying your own project's pypi deps?

**Comment by dsully** [comment]
Yes - those 3 lines are causing issues for us as well. We have conditional requirements in the build system, but unfortunately it doesn't extend to transitive dependencies (yet).

**Comment by gpshead** [comment]
My pull request goes a little further and should make it install a dummy module when installed on Python 3 that just causes subprocess32 to be a reference to the stdlib's subprocess module.

I haven't tested it beyond my test script.

**Comment by gpshead** [comment]
Closing things that are done in the tree.  packaging up a release is tracked in #19.
