### ISSUE TITLE
_args_from_interpreter_flags function not present causes an import error while importing multiprocessing module

### ISSUE THREAD

**Issue by vsnag** [google/python-subprocess32#15]
I did a drop in replacement of python system library subprocess with subprocess32 & renamed the subprocess32 to subprocess in the standard install location. When importing multiprocessing I get an import error

``` python
>>> import multiprocessing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vsnag/Python-2.7.12/Lib/multiprocessing/__init__.py", line 65, in
<module>
    from multiprocessing.util import SUBDEBUG, SUBWARNING
  File "/home/vsnag/Python-2.7.12/Lib/multiprocessing/util.py", line 41, in <mod
ule>
    from subprocess import _args_from_interpreter_flags
ImportError: cannot import name _args_from_interpreter_flags
```

Adding this https://github.com/python/cpython/blob/master/Lib/subprocess.py#L536 could be a possible fix.

**Comment by gpshead** [comment]
We dropped subprocess32 in to replace subprocess in our own internal Python build, adding the _args_from_interpreter_flags function from 2.7's subprocess to the subprocess.py file was indeed the workaround we used.

It didn't seem worth including it in subprocess32 as there is no easy way for people do naturally do this drop-in. But thinking about it, it would let us remove one patch internally in the future and make the drop-in easier for others. I'll consider it.
