### ISSUE TITLE
substitue subprocess32 with subprocess on Debian/Python2.7

### ISSUE THREAD

**Issue by amirteymuri** [google/python-subprocess32#16]
Is the correct way to do it to remove the `/usr/lib/python2.7/subprocess.py` module and replace it with subprocess32? How should i install subprocess32 as default?

**Comment by gpshead** [comment]
If you are building your own Python 2.7 distribution you basically need to add the _posixsubprocess.* files to the Modules/ directory, update the setup.py or Setup.pre.in files (whichever you use) to build the _posixsubprocess module, replace Lib/subprocess.py with with the subprocess32 .py file and replace the Lib/test/test_subprocess* & associated data / helper script files.

Do not do this _on top_ of an existing system such as Debian with python2.7 installed. That'll just be messed up when the package updates. You'd want to do the above within the context of building your own python2.7 interpreter package.

Anyways, this isn't a bug report.  closing.
