### ISSUE TITLE
Use of subprocess32 on MS Windows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/python-subprocess32#2]
```
I'm trying to use the latest version of subprocess32 (3.2.5) on a cross 
platform project and have encountered some problems using the subprocess32 
module on Windows.

OS = Windows 7
Python = 2.7.6

Issue 1: Using the setup.py intsaller fails on Windows because of the posix 
extension modules. Removing the line 
ext_modules=[ext],
from setup.py allows the installation to proceed for windows systems.

Issue 2: The subprocess32 code assumes that _subprocess.c has an attribute 
WAIT_TIMEOUT which isn't the case for Python 2.7 (line 1137 of subprocess32.py)



Nick




```

Original issue reported on code.google.com by `TaeKwonD...@gmail.com` on 24 Mar 2014 at 3:40

**Comment by gpshead** [comment]
Defining the constant and having setup.py not build the extension when not on a posix platform are easy enough. I've made those changes in the depot. BUT... I lack the ability (or time) to test anything on Windows.

This backport was done for POSIX platform reliability reasons. I recommend cross platform projects use a conditional import if they must use Python 2: Just `import subprocess` when running on windows and `import  subprocess32 as subprocess` on linux or other POSIX systems.
