### ISSUE TITLE
call() will only clean up it's opened process if TimeoutExpired thrown but not others

### ISSUE THREAD

**Issue by acannon828** [google/python-subprocess32#28]
e.g. custom Timeout exceptions thrown when entire jobs timeout.

Consider [subprocess32's implementation](https://github.com/google/python-subprocess32/blob/master/subprocess32.py#L294) vs [that for the current Python](https://github.com/python/cpython/blob/master/Lib/subprocess.py#L261).

**Comment by gpshead** [comment]
closing as "won't fix" based on my "My gut feeling is that this is a behavior difference we should just live with rather than backport into subprocess32." comment in the pull request.
