### ISSUE TITLE
Cross-version compatibility for `subprocess.getstatusoutput`

### ISSUE THREAD

**Issue by ncoghlan** [google/python-subprocess32#30]
When Windows support was added to `subprocess.getstatusoutput` we inadvertently made it backwards incompatible with the behaviour of the 2.7 version: https://bugs.python.org/issue22635

Now, backwards compatibility *within* the 3.x series means we can't readily change it back to make it match the Python 2.7 behaviour (even though the only reason it changed in the first place was due to a gap in our test coverage).

This impacts subprocess32 in two ways:

1. You likely want to make sure you *don't* backport that mistake (since it would break migrations from the 2.7 stdlib to `subprocess32`)
2. If `subprocess32` were to support 3.x in addition to 2.7, it could provide a way for affected applications to readily work around the problem

I'm not sure how difficult the latter would be, though.

**Comment by gpshead** [comment]
`getstatusoutput()` is not implemented in `subprocess32` as it is available in the Python 2 `commands` module and was not in the Python 3.2 `subprocess` version this backport originated from.  Later features have been cherry picks.
