### ISSUE TITLE
How to specify dependency to subprocess32?

### ISSUE THREAD

**Issue by guettli** [google/python-subprocess32#37]
I have a library ([subx][1]) which depends on [subprocess32][2]. 

My library needs the timeout kwarg.

I need subprocess32 only if the target platform is Python2.x. 

How should I define the dependency in my project?

I get this error message, if I define a dependency to `subprocess32` via "install_requires" (setup.py) and I am inside a python3 virtualenv:

    ===> pip install -e git+https://github.com/guettli/subx.git#egg=subx
    Obtaining subx from git+https://github.com/guettli/subx.git#egg=subx
      Cloning https://github.com/guettli/subx.git to ./src/subx
    Collecting subprocess32 (from subx)
      Using cached subprocess32-3.2.7.tar.gz
        Complete output from command python setup.py egg_info:
        This backport is for Python 2.x only.
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lju3nl1y/subprocess32/

  [1]: https://github.com/guettli/subx
  [2]: https://pypi.python.org/pypi/subprocess32

Same question here: https://stackoverflow.com/questions/47098185/dependency-management-subprocess32-needed-for-python2-7

**Comment by nirs** [comment]
This may work:

    install_requires = ["subprocess32] if sys.version_info[0] == 2 else []

**Comment by gpshead** [comment]
Something conditional like that makes sense.  I also recently made subprocess32 install as a dummy module that simply acts as an alias for subprocess on Python 3 but that is currently only available in the 3.5.0rc1 release which pip won't pickup by default.  Once I publish 3.5.0 it'll be available everywhere.

https://github.com/google/python-subprocess32/commit/f43fa1102e24db4c725b8dc344a88419573503c8

**Comment by guettli** [comment]
@gpshead yes, make subprocess32 install as a dummy sounds good. Thank you

**Comment by guettli** [comment]
For me (creator of this issue) this is solved. Please reopen if you think not.
