### ISSUE TITLE
Error during pip install on ubuntu

### ISSUE THREAD

**Issue by nscals** [google/python-subprocess32#38]
Subprocess32 is a dependency for the fbprophet library.  

While pip installing the fbprophet module I received the following error:

`Command "/home/ubuntu/anaconda3/envs/resfuture/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-DWKA4l/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-zcj5OE-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-DWKA4l/subprocess32/`

When I tried to pip install just subprocess I encountered the same error: 
`Failed building wheel for subprocess32`
`Command "/home/ubuntu/anaconda3/envs/resfuture/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-paHlZS/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mEbekx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-paHlZS/subprocess32/`

Does anyone know how I can resolve this issue?

**Comment by tungli** [comment]
I had the same error with updating maatplotlib. Installing python-dev solved this for me:
`sudo apt-get install python-dev`

**Comment by skypeter1** [comment]
Solution exposed by @tungli worked for me too

**Comment by Kekushke** [comment]
Solution by @tungli worked for me. Thank you.

**Comment by gpshead** [comment]
Yes, Python headers and a compiler toolchain are required on Linux.

**Comment by vaishnavibala** [comment]
Try this 
`apt-get install -y python-subprocess32`

**Comment by enaosun** [comment]
Solution by @tungli worked for me.
Thanks

**Comment by ryzwannj** [comment]
Solution by @tungli worked for me too
Thanks

**Comment by Rakshith2597** [comment]
Solution by @tungli worked for me as well.
Thanks

**Comment by dkhd** [comment]
It works for me, too. Thank you!

**Comment by kylep** [comment]
I ran into this error trying to install python-openstackclient, on ubuntu 18.04. I had to run `apt-get install gcc` to resolve it.

**Comment by aishwaryap** [comment]
Is there any way to avoid this issue that does not require root access?

**Comment by mayankkhullar** [comment]
Answer by @kylep worked for me !!!

**Comment by Evanlin1224** [comment]
Answer by @tungli  worked to me!!! Thanks guy!!!
