### ISSUE TITLE
Is it possible to pip install this package without compiling C-extension?

### ISSUE THREAD

**Issue by rogalski** [google/python-subprocess32#42]

**Comment by gpshead** [comment]
I'll be providing a binary wheel for macOS users when I push the next release.

But on Linux, no, the only binary option for Linux possible pip and PyPI (manylinux1 and the coming manylinux2) require building against a platform which does not have modern enough APIs for the extension module to be reliable - defeating half the purpose of the module.  Compilation will still be required there.

See issue #14

**Comment by guettli** [comment]
I don't understand this. If you are not able to do build a wheel, then I think I am not able to build a wheel, too. 

I did `python setup.py bdist_wheel` and uploaded this to our local pypi server.

Thinks seem to work this way.

**Comment by gpshead** [comment]
You always can _build_ a wheel.  But you can't make one for subprocess32 that will work on all Linux machines in the world **and** use appropriate modern system call APIs to guarantee it is reliable.

That `bdist_wheel` that you did built a wheel that will work on Linux systems compatible with the one you built it on.  If that's what you need, great for you.

But I can't do that for the global PyPI using manylinux1 or manylinux2 build processes as it would cause everyone to install a less functional module by default.  Building from source on a system equivalent to what you'll be deploying it on (as you did) is always better.
