### ISSUE TITLE
subprocess32 doesn't include updates from 3.7

### ISSUE THREAD

**Issue by Chazzz** [google/python-subprocess32#59]
`>>> subprocess32.run(["ls", "-l"], capture_output=True)`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vincent/.local/lib/python2.7/site-packages/subprocess32.py", line 406, in run
    process = Popen(*popenargs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'capture_output'`

This is not surprising because that's what the code does. However, this behavior has been updated in Python 3.7 (https://docs.python.org/3/library/subprocess.html#subprocess.run, "Changed in version 3.7: Added the text parameter, as a more understandable alias of universal_newlines. Added the capture_output parameter."). In the cpython repository, subprocess.py has been updated with additional parameters (see https://github.com/python/cpython/blob/master/Lib/subprocess.py#L433), that are not present in subprocess32.

While subprocess32 only supporting subprocess up to 3.5 is well documented, there's some additional updates which would be valuable to backport. Thanks!

**Comment by gpshead** [comment]
I'm in no rush to make changes to subprocess32 that would mean people using it are writing code incompatible with widely deployed versions of Python 3 (3.5 and 3.6 are still common).

I suggest just creating your own trivial run function wrapper that implements those args for the time being.

**Comment by Chazzz** [comment]
Haha, yeah that's pretty reasonable. I think I'll implement your suggestion.
